baseURL = 'http://localhost:1313/'
languageCode = 'vi'
title = 'Taf1 IT BLOG'

[params]
  author = 'Nguyễn Thành Tài'
  description = 'Blog Lập Trình Mạng'
  email = 'nguyenthanhtai270604@gmail.com'
  phone = '+84 924 140 389'

[permalinks]
  blog = '/blog/:filename/'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6
